// <auto-generated />
using System;
using Iwannago.Data.EntityFrameworkCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Iwannago.Api.Migrations
{
    [DbContext(typeof(TaxiCabContext))]
    [Migration("20190817173034_newindexes")]
    partial class newindexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Iwannago.Data.Core.Models.TaxiCabTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DOLocationID");

                    b.Property<int>("PULocationID");

                    b.Property<int>("RatecodeID");

                    b.Property<string>("TaxiType");

                    b.Property<string>("VendorID");

                    b.Property<DateTime>("dropoff_datetime");

                    b.Property<string>("ehail_fee");

                    b.Property<decimal>("extra")
                        .HasColumnType("decimal");

                    b.Property<decimal>("fare_amount")
                        .HasColumnType("decimal");

                    b.Property<decimal>("improvement_surcharge")
                        .HasColumnType("decimal");

                    b.Property<decimal>("mta_tax")
                        .HasColumnType("decimal");

                    b.Property<int>("passenger_count");

                    b.Property<int>("payment_type");

                    b.Property<DateTime>("pickup_datetime");

                    b.Property<string>("store_and_fwd_flag");

                    b.Property<decimal>("tip_amount")
                        .HasColumnType("decimal");

                    b.Property<decimal>("tolls_amount")
                        .HasColumnType("decimal");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("decimal");

                    b.Property<decimal>("trip_distance")
                        .HasColumnType("decimal");

                    b.Property<int>("trip_type");

                    b.HasKey("Id");

                    b.HasIndex("TaxiType");

                    b.HasIndex("dropoff_datetime");

                    b.HasIndex("pickup_datetime");

                    b.ToTable("TaxiCabTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
